steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.minimal', '-t', 'europe-west1-docker.pkg.dev/skillforge-ai-mvp-25/skillforge-docker-repo-staging/skillforge-shell:latest', '.']

images:
- 'europe-west1-docker.pkg.dev/skillforge-ai-mvp-25/skillforge-docker-repo-staging/skillforge-shell:latest'