# .github/workflows/build-push-docker.yml
name: "Reusable - Build, Scan, and Push Docker Image"
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      gcp_workload_identity_provider:
        required: true
        type: string
      gcp_service_account:
        required: true
        type: string
    secrets: # <-- DÉCLARATION DES SECRETS REÇUS
      GCP_PROJECT_ID:
        required: true
    outputs:
      image_uri:
        description: "The full URI of the pushed image"
        value: ${{ jobs.build-scan-push.outputs.image_uri }}
jobs:
  build-scan-push:
    name: Build, Scan & Push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      image_uri: ${{ steps.push.outputs.image_uri }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
          service_account: ${{ inputs.gcp_service_account }}
      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
      - name: Build Docker Image
        id: build
        run: |
          IMAGE_URI="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.image_name }}:${{ github.sha }}"
          docker build -t ${IMAGE_URI} -f ${{ inputs.dockerfile_path }} .
          echo "image_uri=${IMAGE_URI}" >> $GITHUB_OUTPUT
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ steps.build.outputs.image_uri }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
      - name: Push Docker Image
        id: push
        run: |
          docker push ${{ steps.build.outputs.image_uri }}
          echo "image_uri=${{ steps.build.outputs.image_uri }}" >> $GITHUB_OUTPUT