# .github/workflows/deploy-to-cloud-run.yml
name: "Reusable - Deploy to Cloud Run"
on:
  workflow_call:
    inputs:
      image_uri:
        required: true
        type: string
      service_name:
        required: true
        type: string
      gcp_region:
        required: true
        type: string
      gcp_workload_identity_provider:
        required: true
        type: string
      gcp_service_account:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
          service_account: ${{ inputs.gcp_service_account }}
      - name: Deploy new revision to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ inputs.service_name }}
          image: ${{ inputs.image_uri }}
          region: ${{ inputs.gcp_region }}
          no-traffic: false