# .github/workflows/deploy-user-service.yml
name: "Deploy - User Service"
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
    paths:
      - 'apps/backend/user-service/**'

jobs:
  test:
    name: Run Unit Tests
    uses: ./.github/workflows/run-python-tests.yml
    with:
      service-directory: 'apps/backend/user-service'
    # Ce job n'a pas besoin de secrets

  build:
    name: Build, Scan & Push Docker Image
    needs: test
    uses: ./.github/workflows/build-push-docker.yml
    with:
      image_name: 'skillforge-docker-repo-staging/user-service'
      dockerfile_path: 'apps/backend/user-service/Dockerfile'
      gcp_workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
      gcp_service_account: ${{ secrets.GCP_CICD_SERVICE_ACCOUNT }}
    secrets: # <-- ON PASSE LES SECRETS NÉCESSAIRES ICI
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  deploy:
    name: Deploy to Cloud Run
    needs: build
    uses: ./.github/workflows/deploy-to-cloud-run.yml
    with:
      image_uri: ${{ needs.build.outputs.image_uri }}
      service_name: 'user-service-staging'
      gcp_region: 'europe-west1'
      gcp_workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
      gcp_service_account: ${{ secrets.GCP_CICD_SERVICE_ACCOUNT }}
    # Ce job n'a pas besoin de secrets car tout est passé via 'with'